### ISSUE TITLE
Click event on map not working

### ISSUE THREAD

**Issue by FazilaMehtab** [fredj/openlayers-heatmap#3]
Hi,

I want add tool tip on map points for that I am using 
 map.on('singleclick', function(evt) {

          });

but its not working and having error :

heatmap.js:52 Uncaught TypeError: map.on is not a function
    at loadMap (heatmap.js:52)
    at heatmap.js

please let me know the solution 

Thanks

**Comment by fredj** [comment]
hi @FazilaMehtab , this project is not maintained anymore because it uses an old version of OpenLayers.
The heatmap feature is now implemented in OpenLayers itself:
https://openlayers.org/en/latest/examples/heatmap-earthquakes.html
